## CharacterTemplate
## Base script for NPC characters.  Uses CharacterAppearanceComponent
## (composition) to manage visual layers, and TopDownMovementComponent for
## movement.  Appearance is driven by a CharacterData resource, which can
## be assigned directly or generated by NpcGenerator.

class_name CharacterTemplate
extends CharacterBody2D

# ---------- Signals ------------------------------------------------------
signal animation_state_changed(anim_name: String, direction: String)

# ---------- Exports ------------------------------------------------------
@export var character_data: CharacterData:
	set(value):
		character_data = value
		if _appearance != null:
			_appearance.character_data = character_data

@export var archetype: CharacterArchetype

# ---------- Onready refs -------------------------------------------------
@onready var _appearance: CharacterAppearanceComponent = $Appearance

# ---------- Internal state -----------------------------------------------
var _current_anim:      String = "idle"
var _current_direction: String = "down"

# ---------- Lifecycle ----------------------------------------------------

func _ready() -> void:
	if character_data == null and archetype != null:
		character_data = NpcGenerator.generate(archetype)
	elif character_data == null:
		character_data = NpcGenerator.generate()

	_appearance.character_data = character_data
	play_animation("idle", "down")

# ---------- Public API ---------------------------------------------------

func play_animation(anim_name: String, direction: String = "down") -> void:
	if _current_anim == anim_name and _current_direction == direction:
		return
	_current_anim      = anim_name
	_current_direction = direction
	_appearance.play_animation(anim_name, direction)
	animation_state_changed.emit(anim_name, direction)

func get_appearance() -> CharacterAppearanceComponent:
	return _appearance
